- name: clone authenz
  git:
   repo: https://github.com/phokz/mod-auth-external.git
   dest: /opt/authen

#This always spits out warnings.
- name: create authenz install files
  shell: apxs -c /opt/authen/mod_authnz_external/mod_authnz_external.c
  ignore_errors: true

- name: activate authenz
  shell: apxs -i -a /opt/authen/mod_authnz_external/mod_authnz_external.la

- name: authen cleanup
  file: path=/opt/authen state=absent

- name: enable apache boot
  service: name=httpd enabled=yes state=started

- name: symlink default dav
  file:
    src: {{apache_dir}}/sites-enabled/default-dav.conf
    dest: {{apache_dir}}/sites-available/default-dav.conf
    state: link
  when: apache_default.stat.exists

- name: restart apache
  service: name=httpd state=restarted

