- block:

  - name: add nginx repo
    apt_repository:
     repo: 'ppa:nginx/stable'

  - name: install nginx
    apt: name=nginx state=present
    notify:
     - enable nginx boot
     - monitor nginx
     - restart nginx

  - name: create nginx group
    group: name=nginx state=present

  - name: create nginx user
    user: name=nginx group=nginx state=present

  - name: remove unsupported aio
    replace:
      dest: "{{item}}"
      regexp: '^\s*-aio'
      replace: "#aio on; #turn off aio for ubuntu"
    with_items:
     - /etc/nginx/apps/drupal/drupal.conf
     - /etc/nginx/apps/drupal/drupal_boost.conf
     - /etc/nginx/apps/drupal/drupal_boost_escaped.conf
     - /etc/nginx/apps/drupal/drupal_burris.conf
     - /etc/nginx/apps/drupal/drupal_dev.conf
     - /etc/nginx/apps/drupal/drupal_live.conf
     - /etc/nginx/apps/drupal/drupal_stage.conf
    notify:
     - restart nginx

  tags:
   - dev
   - live