- block:

  - name: install language pack to avoid ondrej errors
    apt: name=language-pack-en-base state=present

  - name: get ondrej repo
    apt_repository:
     repo: 'ppa:ondrej/php'


  - name: install php-fpm
    apt: name=php7.0-fpm state=installed
    notify:
     - restart ubuntu php-fpm

  tags:
   - dev
   - live
   - php-fpm