- block:

  - name: install language pack to avoid ondrej errors
    apt: name=language-pack-en-base state=present

  - name: get ondrej repo
    apt_repository:
     repo: 'ppa:ondrej/php'


  - name: install php 70 packages
    apt: name={{ item }} state=installed
    with_items:
    - php-pear
    - php7.0-common
    - php7.0-cli
    - php7.0-dev
    - php7.0-gd
    - php7.0-intl
    - php7.0-mbstring
    - php7.0-mysqlnd
    - php7.0-opcache
    - php7.0-soap
    - php7.0-tidy
    - php7.0-xmlrpc
    - php7.0-zip
    register: php

  - name: install php-fpm
    apt: name=php7.0-fpm state=installed
    notify:
     - restart php-fpm 70
     - enable php-fpm 70
     - monitor php-fpm 70

  tags:
   - dev
   - live
   - php-fpm

- block:

  - name: set pecl 7 vars
    command: /usr/bin/pecl config-set php_ini /etc/php/7.0/fpm/php.ini

  - name: set pear 7 vars
    command: /usr/bin/pear config-set php_ini /etc/php/7.0/fpm/php.ini

  when: php.changed
  tags:
   - dev
   - live

#This is primarily for php cli (composer) since pools contain their own memory setting.
- name: set php memory limit
  lineinfile:
    dest: /etc/php/7.0/fpm/php.ini
    regexp: '^memory_limit'
    line: 'memory_limit = 512M'
    state: present
  tags:
   - devs
   - live

#Create composer ini before xdebug is installed
- name: create composer ini
  copy: src=/etc/php/7.0/fpm/php.ini dest=/etc/php/7.0/fpm/php-composer.ini
  when: php.changed
  tags:
   - dev

- block:

  - name: stat xdebug
    stat: path=/usr/lib/php/20151012/xdebug.so
    register: xdebug

  - name: install xdebug
    command: /usr/bin/pecl install xdebug
    when: not xdebug.stat.exists
    register: xdebug_install

  - name: chmod xdebug
    file: path=/usr/lib/php/20151012/xdebug.so mode=o+x
    when: xdebug_install.changed

  tags:
   - dev
   - xdebug