---

#PHP Install and settings.
- include: "{{ansible_os_family}}.yml"

- name: include family values
  include_vars:
    file: "{{ansible_os_family}}.yml"
  tags:
   - always

#Setup session directories
- name: dev session
  file: path=/var/lib/php/{{php_version}}/session-dev state=directory owner=nginx group=nginx mode=0770
  tags:
   - dev

- name: stage session
  file: path=/var/lib/php/{{php_version}}/session-stage state=directory owner=nginx group=nginx mode=0770
  tags:
   - dev

- name: live session
  file: path=/var/lib/php/{{php_version}}/session-live state=directory owner=nginx group=nginx mode=0770
  tags:
   - dev
   - live

- name: builder session
  file: path=/var/lib/php/{{php_version}}/session-burrisx state=directory owner=nginx group=nginx mode=0770
  tags:
   - burris_builder


...