---

#PHP Install and settings.
- include: "{{ansible_os_family}}.yml"

- name: include family values
  include_vars:
    file: "{{ansible_os_family}}.yml"
  tags:
   - always

- name: include vagrant vars
  include_vars: file=vagrant.yml
  tags:
   - vagrant

- name: setup log directory
  file: path={{ php_log_dir }} state=directory
  tags:
   - dev
   - live

- name: setup dev session directories
  file: path={{ php_session_dir }}/{{ item }} state=directory owner={{nginx_user}} group=nginx mode=0770
  with_items:
   - session-dev
   - session-stage
   - session-live
  tags:
   - dev

- name: setup live session directories
  file: path={{ php_session_dir }}/session-live state=directory owner=nginx group=nginx mode=0770
  tags:
   - live

- name: setup burris builder session directory
  file: path={{ php_session_dir }}/session-burrisx state=directory owner=nginx group=nginx mode=0770
  tags:
   - burris_builder


#Setup Pools
- name: setup dev pool
  template: src=www.conf.j2 dest={{php_fpm_pool_dir}}/www-dev.conf
  vars:
    pool_name: "{{ pool_dev_name }}"
    pool_user: "{{ nginx_user }}"
    pool_group: "{{ nginx_group }}"
    php_port: "{{ php_dev_port }}"
    php_addr: "{{ php_dev_addr }}"
    php_memory: "{{ php_dev_memory }}"
    php_errors: "{{ php_dev_errors }}"
    php_session: "{{ php_session_dir }}/session-dev"
    php_log: "{{ php_log_dir }}/wwwdev-error.log"
  tags:
  - dev

- name: setup stage pool
  template: src=www.conf.j2 dest={{php_fpm_pool_dir}}/www-stage.conf
  vars:
    pool_name: "{{ pool_stage_name }}"
    pool_user: "{{ nginx_user }}"
    pool_group: "{{ nginx_group }}"
    php_port: "{{ php_stage_port }}"
    php_addr: "{{ php_stage_addr }}"
    php_memory: "{{ php_stage_memory }}"
    php_errors: "{{ php_stage_errors }}"
    php_session: "{{ php_session_dir }}/session-stage"
    php_log: "{{ php_log_dir }}/wwwstage-error.log"
  tags:
  - dev

- name: setup live pool
  template: src=www.conf.j2 dest={{php_fpm_pool_dir}}/www.conf
  vars:
    pool_name: "{{ pool_live_name }}"
    pool_user: "{{ nginx_user }}"
    pool_group: "{{ nginx_group }}"
    php_port: "{{ php_live_port }}"
    php_addr: "{{ php_live_addr }}"
    php_memory: "{{ php_live_memory }}"
    php_errors: "{{ php_live_errors }}"
    php_session: "{{ php_session_dir }}/session-live"
    php_log: "{{ php_log_dir }}/error.log"
  tags:
  - dev
  - live

- name: setup burrisx pool
  template: src=www.conf.j2 dest={{php_fpm_pool_dir}}/burrisx.conf
  vars:
    pool_name: "{{ pool_bb_name }}"
    pool_user: burrisx
    pool_group: burrisx
    php_port: "{{ php_bb_port }}"
    php_addr: "{{ php_bb_addr }}"
    php_memory: "{{ php_bb_memory }}"
    php_errors: "{{ php_bb_errors }}"
    php_session: "{{ php_session_dir }}/session-burrisx"
    php_log: "{{ php_log_dir }}/wwwburrisx-error.log"
  tags:
  - burris_builder

...