---

- block:

  - name: install php packages
    yum: name={{ item }} state=installed
    with_items:
    - php56
    - php56-dba
    - php56-devel
    - php56-gd
    - php56-intl
    - php56-mbstring
    - php56-mysqlnd
    - php56-opcache
    - php56-pdo
    - php56-pecl-http
    - php56-pecl-http-devel
    - php56-pecl-imagick
    - php56-jsonc
    - php56-jsonc-devel
    - php56-pecl-ssh2
    - php56-soap
    - php56-tidy
    - php56-xmlrpc
    - php56-pecl-memcache
    - php56-pecl-memcached
    notify:
     - enable php-fpm 56
     - restart php-fpm 56
     - monitor php-fpm 56
    tags:
     - dev
     - live
     - php
    register: php

  - name: install php-fpm
    yum: name=php56-fpm state=installed
    notify:
     - restart php-fpm 56
     - restart php-fpm 56
     - enable php-fpm boot
     - monitor php-fpm
    tags:
     - dev
     - live
     - php-fpm

  - block:

    - name: set pecl 56 vars
      command: /usr/bin/pecl config-set php_ini /etc/php.ini

    - name: set pear 56 vars
      command: /usr/bin/pear config-set php_ini /etc/php.ini

    when: php.changed
    tags:
     - dev
     - live


  #This is primarily for php cli (composer) since pools contain their own memory setting.
  - name: set php memory limit
    lineinfile:
     dest: /etc/php.ini
     regexp: '^memory_limit'
     line: 'memory_limit = 512M'
     state: present
    tags:
     - dev
     - live


  #Create composer ini before xdebug is installed
  - name: create composer ini
    copy: src=/etc/php.ini dest=/etc/php-composer.ini
    tags:
     - dev

  when: php_version == 5.6

- block:

  - name: stat xdebug
    stat: path=/usr/lib64/php/5.6/modules/xdebug.so
    register: xdebug

  - name: install xdebug
    command: /usr/bin/pecl install xdebug
    when: not xdebug.stat.exists

  tags:
   - dev
  when: php_version == 5.6


...