- name: install apache
  yum: name={{item}} state=present
  with_items:
   - httpd24
   - httpd24-tools
   - perl-CPAN
   - perl-Authen-PAM
   - mod24_ssl
   - perl-libwww-perl
   - perl-App-cpanminus
  notify:
   - enable apache boot
   - restart apache
  tags:
   - apache
   - webdav

#devel includes apxs, which allows authen install
- name: install devel tools
  yum: name=httpd24-devel state=present
  notify:
   - clone authenz
   - create authenz install files
   - activate authenz
   - authen cleanup
   - restart apache
  tags:
   - webdav

#Activate volume, if attached.
#This doesn't detect "mounted" specifically, for easy local environment
#replication.
- block:
  - name: stat app drive
    stat: path=/www
    register: appdrive

  - name: sym apache volume
    file:
     src: /etc/httpd/sites-available/volumes/www.conf
     dest: /etc/httpd/sites-enabled/www.conf
     state: link
    when: appdrive.stat.exists

  tags:
   - webdav
   - apache

- block:
  - name: stat apache git repo
    stat: path=/etc/httpd/.git
    register: apache_repo

  - name: clear apache directory
    file: path=/etc/httpd state=absent
    when: not apache_repo.stat.exists

  - name: clone apache config
    git:
      repo: https://github.com/wwwpro/httpd.git
      dest: /etc/httpd
    when: not apache_repo.stat.exists

  tags:
   - webdav
   - apache

- name: check for bb apache config
  stat: path=/etc/httpd/.git
  register: apache_default
  tags:
   - default
   - builder_dev

- name: symlinking default webdav
  file:
    src: /etc/httpd/sites-enabled/default-dav.conf
    dest: /etc/httpd/sites-available/default-dav.conf
    state: link
  when: apache_default.stat.exists
  tags:
   - default

- name: symlinking default webdav
  file:
    src: /etc/httpd/sites-enabled/burris_builder-dav.conf
    dest: /etc/httpd/sites-available/burris_builder-dav.conf
    state: link
  when: apache_default.stat.exists
  tags:
   - builder_dev