- name: including vars file
  include_vars: "{{ansible_os_family}}.yml"
  tags:
   - always

- name: including apache task file
  include: "{{ansible_os_family}}.yml"


#Activate volume, if attached.
#This doesn't detect "mounted" specifically, for easy local environment
#replication.
- block:
  - name: stat app drive
    stat: path=/www
    register: appdrive

  - name: sym apache volume
    file:
     src: /etc/httpd/sites-available/volumes/www.conf
     dest: /etc/httpd/sites-enabled/www.conf
     state: link
    when: appdrive.stat.exists

  tags:
   - webdav
   - apache


- name: stat apache git repo
  stat: path={{apache_dir}}/.git
  register: apache_repo
  tags:
   - webdav

#Clone configuration.
- block:

  - name: clear apache directory
    file: path={{apache_dir}} state=absent
    when: not apache_repo.stat.exists

  - name: clone apache config
    git:
      repo: https://github.com/wwwpro/httpd.git
      dest: "{{apache_dir}}"

  when: not apache_repo.stat.exists
  tags:
   - webdav

- name: stat apache git repo again
  stat: path={{apache_dir}}/.git
  register: apache_repo
  tags:
   - webdav

#Create dav-digest and dbm for ports 81 and 444 webdav, respectively.
- block:

  - name: get md5 password
    shell:  echo -n {{user_pass}} | md5sum | awk '{print $0}' | cut -f1 -d ' '
    register: md5_pass

  - name: create webdav digest
    lineinfile:
      create: yes
      line: "{{user_name}}:WebDav:{{md5_pass.stdout}}"
      dest: "{{auth_dir}}/.dav-digest"

  - name: create webdav dbm
    shell: "/usr/bin/htdbm -cb {{auth_dir}}/.dbm {{user_name}} {{user_pass}}"

  tags:
   - webdav


# Webdav default
- block:

  - name: replace default dav
    template:
      src: default-dav.conf.j2
      dest: "{{apache_dir}}/sites-available/default-dav.conf"

  - name: symlink default dav
    file:
      src: "{{apache_dir}}/sites-available/default-dav.conf"
      dest: "{{apache_dir}}/sites-enabled/default-dav.conf"
      state: link

  - name: restoring logs symlink
    file:
      src: /var/log/httpd
      dest: /etc/httpd/logs
      state: link

  - name: restoring modules symlink
    file:
      src: /usr/lib64/httpd/modules
      dest: /etc/httpd/modules
      state: link

  - name: restoring run symlink
    file:
      src: /var/run/httpd
      dest: /etc/httpd/run
      state: link
  tags:
   - webdav
  when: apache_repo.stat.exists


- name: check for baws apache config
  stat: path={{apache_dir}}/.git
  register: apache_default
  tags:
   - always

- name: remove current default if exists
  file: name={{apache_dir}}/sites-available

- name: create default site conf
  template: src=default-dav.conf.j2 dest={{apache_dir}}/sites-available/default-dav.conf

- name: symlinking default webdav
  file:
    src: /etc/httpd/sites-enabled/burris_builder-dav.conf
    dest: /etc/httpd/sites-available/burris_builder-dav.conf
    state: link
  when: apache_default.stat.exists
  tags:
   - builder_dev
