include: vars/RedHat.yml

- name: install apache
  yum: name={{item}} state=present
  with_items:
   - httpd24
   - httpd24-tools
   - perl-CPAN
   - perl-Authen-PAM
   - mod24_ssl
   - perl-libwww-perl
   - perl-App-cpanminus
  notify:
   - enable apache boot
   - restart apache
  tags:
   - apache
   - webdav

#devel includes apxs, which allows authen install
- name: install devel tools
  yum: name=httpd24-devel state=present
  notify:
   - clone authenz
   - create authenz install files
   - activate authenz
   - authen cleanup
   - restart apache
  tags:
   - webdav