--- #Sets up server from ansible pull.

- name: setup server
  hosts: "{{host}}"
  remote_user: "{{ssh_user}}"
  become: true
  pre_tasks:
  - name: update all yum packages
    yum:
      name: "*"
      state: latest
    tags:
     - always

  - name: install basic packages
    yum: name={{ item }} state=installed
    with_items:
    - gcc
    - gcc-c++
    - jemalloc
    - jemalloc-devel
    tags:
     - always

  - name: install yum cron
    yum: name=yum-cron state=installed
    register: yumcron
    notify:
     - enable yum cron
     - start yum cron
    tags:
     - always


  - name: sed yum cron
    lineinfile:
     dest: /etc/yum/yum-cron.conf
     state: present
     regexp: '^apply_updates'
     line: 'apply_updates = yes'
    when: yumcron.changed
    tags:
     - always

  - name: sed yum security
    lineinfile:
     dest: /etc/yum/yum-cron.conf
     state: present
     regexp: '^update_cmd'
     line: 'update_cmd = security'
    when: yumcron.changed
    tags:
     - live

  roles:
  - common
  - users
  - ec2
  - codedeploy
  - awslogs
  - apache
  - mysql
  - nginx
  - php-fpm
  - composer
  - drupal
  - burris_builder
  - wp
  - webtools
  - websites
  - monit
  - gluster
  - jenkins
  - slack

  handlers:

  - name: enable yum cron
    service: name=yum-cron enabled=yes

  - name: start yum cron
    service: name=yum-cron state=started
...