--- #Sets up server from ansible pull.

- name: setup server
  hosts: "{{host_name | default ('localhost')}}"
  remote_user: "{{ssh_user}}"
  become: true
  pre_tasks:
  - include: "{{ansible_os_family}}.yml"
  roles:
   - awslogs
   - users
   - common
   - composer
   - memcached
   - slack
   - ec2
   - cloudwatch
   - codedeploy
   - webtools
   - drupal
   - wp
   - websites
   - burris_builder
   - nginx
   - php-fpm
...