--- #Sets up server from ansible pull.

- name: setup server
  hosts: localhost
  remote_user: "{{ssh_user}}"
  become: true
  group_by: key=family_{{ansible_os_family}}
  pre_tasks:
  - include: "{{ansible_os_family}}.yml"

  roles:
   - nginx
...