--- #Sets up server from ansible pull.

- name: setup server
  hosts: "{{host_name | default ('localhost')}}"
  remote_user: "{{ssh_user}}"
  become: true
  pre_tasks:
  - include: "{{ansible_os_family}}.yml"

  roles:
   - common
   - nginx
   - php-fpm
...