- name: install monit
  apt: name=monit state=present
  notify:
   - activate monit host
   - enable monit boot
   - restart monit

- name: set alert file
 template: src=alert.cfg.j2 dest=/etc/monit/conf.d/alert.cfg

- name: set email config
 template: src=mail.cfg.j2 dest=/etc/monit/conf.d/mail.cfg
 when: ses_user != none