- name: install patch
  yum: name=patch state=present
  tags:
   - dev

- name: install npm
  yum: name=npm state=present enablerepo=epel
  notify:
   - install npm grunt
   - install npm bower
  tags:
   - dev
   - npm

#Install Webmin
- block:
  - name: install webmin
    copy: src=webmin.repo dest=/etc/yum.repos.d/webmin.repo

  - name: import jcameron key
    rpm_key: key=http://www.webmin.com/jcameron-key.asc state=present

  - name: install webmin yum
    yum: name=webmin state=present

  tags:
   - webmin