# todo: what was installing this before? It's not installing.
- name: set pear vars
  shell: /usr/bin/pear config-set php_ini /etc/php.ini

- name: enable php-fpm boot
  service: name=php-fpm-7.0 enabled=yes

- name: restart php-fpm
  service: name=php-fpm-7.0 state=restarted