- name: install mysql server
  apt: name=mysql-server-5.6 state=present
  notify:
   - install my cnf
   - enable mysql boot
   - restart mysql
   - create root pass
   - installing pip mysql
   - create root cnf
  tags:
   - mysql
   - local

- name: install mysql command
  apt: name=mysql56 state=present
  tags:
   - mysql
   - dev
   - live
   - local

- meta: flush_handlers