- name: install mysql server
  apt: name=mysql-server-5.6 state=present
  notify:
   - enable mysql boot
   - install pip mysql
   - restart mysql
  tags:
   - mysql
   - local

- meta: flush_handlers