- name: install mysql server
  apt: name=mysql-server-5.6 state=present
  notify:
   - enable mysql boot
   - install pip mysql
   - restart mysql
  tags:
   - mysql
   - local

- name: install python mysql
  apt: name=python-mysqldb
  tags:
   - mysql
   - local
   - mysql_import

- meta: flush_handlers