- include: "{{ansible_os_family}}.yml"

- block:

  - name: create root pass
    mysql_user:
     name: root
     password: "{{local_mysql_root}}"
     host: localhost
     check_implicit_admin: yes

  - name: create root cnf
    template: src=root.cnf.j2 dest=/root/.my.cnf mode=0600

  when: mysql_pass is defined
  tags:
   - mysql


- name: install my cnf
  copy: src=my.cnf dest=/etc
  tags:
   - mysql
   - local