- include: "{{ansible_os_family}}.yml"

- block:

  - name: create root pass
    mysql_user:
     name: root
     password: "{{local_mysql_root}}"
     host: localhost
     check_implicit_admin: yes

  - name: create root cnf
    template: src=root.cnf.j2 dest=/root/.my.cnf mode=0600

  when: mysql_root_pass is defined
  tags:
   - mysql
   - local

- name: install my cnf
  copy: src=my.cnf dest={{mysql_cnf}}

- block:

  - name: create mysql database
    mysql_db:
      name: "{{mysql_db}}"

  - name: create mysql user
    mysql_user:
      name: "{{mysql_user}}"
      password: "{{mysql_pass}}"
      priv: '{{mysql_db}}.*:ALL'
  tags:
   - mysql
   - local

- name: import mysql database
  mysql_db:
    name: "{{mysql_db}}"
    state: import
    target: "{{mysql_import_dir}}/{{mysql_import_file}}"
  tags:
   - mysql_import
   - drupal7_import
   - wp_import



