- name: installing mysql python
  yum: name=MySQL-python27 state=present
  tags:
   - mysql
   - dev
   - live

- name: install pip mysql
  pip: name=MySQL-python state=present
  tags:
   - mysql
   - local

- name: install mysql server
  yum: name=mysql56-server state=present
  notify:
   - enable mysql boot
   - restart mysql
  tags:
   - mysql

- name: install mysql command
  yum: name=mysql56 state=present
  tags:
   - mysql
   - dev
   - live

- meta: flush_handlers