- name: enable nginx boot
  service: name=nginx enabled=yes state=started

- name: symlink pma
  file:
   src: /etc/nginx/sites-available/pma.conf
   dest: /etc/nginx/sites-enabled/pma.conf
   state: link

- name: enable site
  file: src={{site_available}}/{{site_name}}.conf dest={{site_enabled}}/{{site_name}}.conf state=link

- name: restart nginx
  service: name=nginx state=restarted