- name: enable nginx boot
  service: name=nginx enabled=yes state=started

- name: symlink pma
  file:
   src: /etc/nginx/sites-available/pma.conf
   dest: /etc/nginx/sites-enabled/pma.conf
   state: link

- name: enable site
  file: src={{site_available}}/{{site_name}}.conf dest={{site_enabled}}/{{site_name}}.conf state=link

- name: symlink default site
  file:
    src: /etc/nginx/sites-available/default.conf
    dest: /etc/nginx/sites-enabled/default.conf
    state: link
  ignore_errors: true

- name: remove unsupported aio
  replace:
    dest: "{{item}}"
    regexp: '^\s*[#]?aio'
    replace: "#aio on; #turn off aio for ubuntu"
  with_items:
   - /etc/nginx/apps/drupal/drupal.conf
   - /etc/nginx/apps/drupal/drupal_boost.conf
   - /etc/nginx/apps/drupal/drupal_boost_escaped.conf
   - /etc/nginx/apps/drupal/drupal_burris.conf
   - /etc/nginx/apps/drupal/drupal_dev.conf
   - /etc/nginx/apps/drupal/drupal_live.conf
   - /etc/nginx/apps/drupal/drupal_stage.conf

- name: restart nginx
  service: name=nginx state=restarted