- name: send slack notification
  slack:
    token: "{{slack_token}}"
    msg: "<a href=\"https://{{ansible_ec2_placement_region}}.console.aws.amazon.com/ec2/v2/home?region={{ansible_ec2_placement_region}}#Instances:search={{ansible_ec2_instance_id}};sort=availabilityZone\">{{ansible_ec2_instance_id}}</a> has completed </br>
    SSH: ec2-user@{{ansible_ec2_public_hostname}}"
  when: slack_token != 'none'
  tags:
   - always