- name: get jenkins repo
  get_url:
   url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
   dest: /etc/yum.repos.d/jenkins.repo
  tags:
   - jenkins

- name: import jenkins key
  rpm_key: key=https://jenkins-ci.org/redhat/jenkins-ci.org.key state=present
  tags:
   - jenkins

- name: install jenkins
  yum: name=jenkins state=present
  tags:
   - jenkins
  notify:
   - enable jenkins boot

