---
- block:

  - name: install aws logs
    yum: name=awslogs state=present
    notify:
     - enable awslogs boot
     - restart awslogs

  - name: create aws logs conf
    copy: src=awslogs.conf dest=/etc/awslogs/awslogs.conf

  when: "'amazon' in ansible_product_version"
  tags:
   - live
   - awslogs
...