; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.34"

; Modules
projects[ctools][version] = "1.4"

projects[admin_menu][version] = "3.0-rc4"

projects[backup_migrate][version] = "2.8"

projects[devel][version] = "1.5"

projects[email][version] = "1.3"

projects[entity][version] = "1.5"

projects[field_group][version] = "1.3"

projects[jquery_update][version] = "2.4"

projects[libraries][version] = "2.2"

projects[module_filter][version] = "2.0-alpha2"

projects[navbar][version] = "1.4"

projects[variable][version] = "2.5"

projects[views][version] = "3.8"

; Themes
projects[ember][version] = "2.0-alpha2"

;projects[shiny][version] = "1.5"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = "git"
libraries[backbone][download][url] = "https://github.com/jashkenas/backbone.git"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = "git"
libraries[underscore][download][url] = "https://github.com/jashkenas/underscore.git"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = "git"
libraries[modernizr][download][url] = "https://github.com/Modernizr/Modernizr.git"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"
libraries[modernizr][tag] = "v2.8.3"

projects[burris_builder][type] = "module"
projects[burris_builder][download][type] = "git"
projects[burris_builder][download][url] = "https://github.com/wwwpro/burris-builder.git"