- name: gather ec2 facts
  action: ec2_facts
  tags:
   - always

- name: get public key
  authorized_key: user={{ssh_user}} key={{public_key_url}}
  when: public_key_url is defined
  tags:
   - always

#@todo Causes syntax errors. Why?
#- name: set timezone
#  timezone: name=America/Los_Angeles
#  tags:
#   - always


- include: "{{ansible_os_family}}.yml"

#Install pasword resources
- block:

  - name: install python passlib
    pip: name=passlib state=present

  - name: create auth directory
    file: path=/var/www/auth state=directory

  - name: create resources file
    htpasswd: name={{user_name}} password={{user_pass}} path=/var/www/auth/.resources

  - name: create dbm file
    shell: htdbm -cb /var/www/auth/.dbm "{{user_name}}" "{{user_pass}}"
    args:
      creates: /var/www/auth/.dbm

  - name: create root cnf
    template: src=resources.j2 dest=/root/.resources mode=0600

  tags:
   - live
   - dev
   - webtools
   - jenkins
   - gluster