- name: enable mysql boot
  service: name=mysqld enabled=yes state=started

- name: install pip mysql
  pip: name=MySQL-python state=present

- name: restart mysql
  service: name=mysqld state=restarted