- name: include vagrant vars
  include_vars: vagrant.yml
  tags:
   - vagrant

- stat: path=/usr/bin/drush
  register: drush
  tags:
   - drush
   - dev
   - burris_builder
   - drupal7_site
   - drupal8_site

- name: install drush
  get_url: url=http://files.drush.org/drush.phar dest=/usr/bin/drush mode=ugo+x
  notify:
   - initial drush run
  when: not drush.stat.exists
  tags:
   - drush
   - dev
   - burris_builder
   - drupal_site


#Should be set with vars db_name db_user db_pass and db_host
- name: create drupal settings.php
  template: src=drupal.settings.j2 dest={{ site_root }}/sites/default/settings.php
  tags:
   - drupal7_site