- name: include vagrant vars
  include_vars: vagrant.yml
  tags:
   - vagrant

- stat: path=/usr/bin/drush
  register: drush
  tags:
   - drush
   - dev
   - burris_builder
   - drupal7
   - drupal8

- name: install drush
  get_url: url=http://files.drush.org/drush.phar dest=/usr/bin/drush mode=ugo+x
  notify:
   - initial drush run
  when: not drush.stat.exists
  tags:
   - drush
   - dev
   - burris_builder
   - drupal_site


- name: setting drupal settings according to import
  template: src=drupal.settings.j2 dest={{ site_root }}/{{site_name}}/sites/default/settings.php
  vars:
   db_name: "{{mysql_db}}"
   db_user: "{{mysql_user}}"
   db_pass: "{{mysql_pass}}"
  tags:
   - local_db_import

- name: composer install
  become_user: "{{ssh_user}}"
  shell: composer install --no-interaction --prefer-dist
  args:
    creates: "/var/www/html/{{site_name}}/vendor"
  tags:
   - composer_install